version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
#    volumes:
#      - ./:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py loaddata printers_data.json &&
             python3 manage.py runserver 0.0.0.0:8000"

    env_file:
      - .env
    depends_on:
      - db
      - redis
      - wkhtmltopdf
  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
  db:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    env_file:
      - .env
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
      - "32768:32768"
    env_file:
      - .env
